Added support for bedrock servers
xrjr/mcutils pull request #15
Opened 2022-05-14 14:05 UTC by AlexBrin

2022-05-16 10:10 UTC, xrjr requested changes
This PR adds a great feature, but needs some adjustments before being merged.

I really appreciate your contribution and the way you built your implementation using existing methods and naming conventions. Thanks a lot !

2022-05-16 10:10 UTC, xrjr commented on pkg/bedrock/client.go
> +		return nil, errors.New("empty response")
Declare errors globally

2022-05-16 10:10 UTC, xrjr commented on pkg/bedrock/client.go
> +	// TODO: if server-name or motd contains a ';' it is no escaped, and will break this parsing
I can't merge code that can break

2022-05-16 10:10 UTC, xrjr commented on pkg/bedrock/bedrock.go
> +			_, _ = fmt.Fprintln(os.Stderr, "Disconnect error: ", err.Error())
We don't want this library to print to standard output

2022-05-16 10:10 UTC, xrjr commented on pkg/bedrock/client.go
> +	// Yes, it looks disgusting, but I think this is the best option to parse the response
This comment isn't really reassuring. Is this method robust ?

2022-05-16 10:10 UTC, xrjr commented on pkg/bedrock/client.go
> +		return nil, errors.New("first byte is not id_unconnected_pong")
Declare errors globally

2022-05-16 10:10 UTC, xrjr commented on pkg/bedrock/client.go
> +		return nil, errors.New("magic bytes do not match")
Declare errors globally

2022-05-16 14:29 UTC, AlexBrin commented on pkg/bedrock/client.go
> +		return nil, errors.New("empty response")
Sorry, I didn't pay attention to the existing errors. Declared everything globally

2022-05-16 14:29 UTC, AlexBrin commented on pkg/bedrock/bedrock.go
> +			_, _ = fmt.Fprintln(os.Stderr, "Disconnect error: ", err.Error())
Done

2022-05-16 14:30 UTC, AlexBrin commented on pkg/bedrock/client.go
> +	// TODO: if server-name or motd contains a ';' it is no escaped, and will break this parsing
This will not lead to a fatal error. In this case, the error lies only in incorrect parsing
Maybe there are ideas how this can be handled?

2022-05-16 14:32 UTC, AlexBrin commented on pkg/bedrock/client.go
> +	// Yes, it looks disgusting, but I think this is the best option to parse the response
Unfortunately, this is the only method of analyzing the server response. It comes in the format "MCPE;motd of the server;protocol version;etc...". But due to the simplicity of the server software, everyone who is not lazy makes their forks and can change the answer as they like. There is no single standard

2022-05-18 08:42 UTC, xrjr commented
I can't merge it to master yet. I'll merge it to a new branch `add-support-for-bedrock-servers` and try to improve parsing. Thank you for your contribution.

2022-05-18 08:44 UTC, merged